[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = '''
	  max-age=63072000;
	  includeSubDomains;
	  preload'''

[[redirects]]
  from = "/arc-sw.js"
  to = "https://arc.io/arc-sw.js"
  status = 200