version: 2.1

orbs:
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.7.0


jobs:
  install:
    # These next lines define a Docker executor: https://circleci.com/docs/2.0/executor-types/
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages

  clean:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Clean files
          command: npm run clean

  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Run build
          command: npm run build


workflows:
  build:
    jobs:
      - install
      - clean
      - build
