version: 2.1

orbs:
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.7.0


jobs:
  build:
    docker:
      - image: cimg/node:lts
    resource_class: small
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Clean files
          command: npm run clean
      - run:
          name: Run build
          command: npm run build


workflows:
  build:
    jobs:
      - build
